CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 2_1.cpp -o 2_1.o 
	$(CC) $(CFLAGS) 2_3.cpp -o 2_3.o 
	$(CC) $(CFLAGS) 2_8.cpp -o 2_8.o 
	$(CC) $(CFLAGS) 2_13.cpp -o 2_13.o 
	$(CC) $(CFLAGS) 2_17.cpp -o 2_17.o 
clean:
	rm -rf *.o
