CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) Person.cpp -o person.o 
	$(CC) $(CFLAGS) Screen.cpp -o screen.o 
	$(CC) $(CFLAGS) 7_31.cpp -o 7_31.o 
	$(CC) $(CFLAGS) WindowManager.cpp -o windowmanager.o 

clean:
	rm -rf *.o
