CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 3_14.cpp -o 3_14.o 
	$(CC) $(CFLAGS) 3_15.cpp -o 3_15.o 
	$(CC) $(CFLAGS) 3_17.cpp -o 3_17.o 
	$(CC) $(CFLAGS) 3_20.cpp -o 3_20.o 
clean:
	rm -rf *.o
