CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 3_1.cpp -o 3_1.o 
	$(CC) $(CFLAGS) 3_2.cpp -o 3_2.o 
	$(CC) $(CFLAGS) 3_4.cpp -o 3_4.o 
	$(CC) $(CFLAGS) 3_5.cpp -o 3_5.o 
	$(CC) $(CFLAGS) 3_6.cpp -o 3_6.o 
	$(CC) $(CFLAGS) 3_7.cpp -o 3_7.o 
	$(CC) $(CFLAGS) 3_8.cpp -o 3_8.o 
	$(CC) $(CFLAGS) 3_10.cpp -o 3_10.o 
clean:
	rm -rf *.o
