CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 10_1.cpp -o 10_1.o 
	$(CC) $(CFLAGS) 10_2.cpp -o 10_2.o 
	$(CC) $(CFLAGS) 10_3.cpp -o 10_3.o 
	$(CC) $(CFLAGS) 10_4.cpp -o 10_4.o 
	$(CC) $(CFLAGS) 10_6.cpp -o 10_6.o 
	$(CC) $(CFLAGS) 10_9.cpp -o 10_9.o 
	$(CC) $(CFLAGS) 10_11.cpp -o 10_11.o 
	$(CC) $(CFLAGS) 10_13.cpp -o 10_13.o 
	$(CC) $(CFLAGS) 10_16.cpp -o 10_16.o 
	$(CC) $(CFLAGS) 10_18.cpp -o 10_18.o 
	$(CC) $(CFLAGS) 10_19.cpp -o 10_19.o 
	$(CC) $(CFLAGS) 10_20.cpp -o 10_20.o 
	$(CC) $(CFLAGS) 10_22.cpp -o 10_22.o 
	$(CC) $(CFLAGS) 10_24.cpp -o 10_24.o 
	$(CC) $(CFLAGS) 10_25.cpp -o 10_25.o 
	$(CC) $(CFLAGS) 10_27.cpp -o 10_27.o 
	$(CC) $(CFLAGS) 10_28.cpp -o 10_28.o 
	$(CC) $(CFLAGS) 10_29.cpp -o 10_29.o
	$(CC) $(CFLAGS) 10_30.cpp -o 10_30.o
	$(CC) $(CFLAGS) 10_31.cpp -o 10_31.o
	$(CC) $(CFLAGS) 10_33.cpp -o 10_33.o
	$(CC) $(CFLAGS) 10_34.cpp -o 10_34.o
	$(CC) $(CFLAGS) 10_35.cpp -o 10_35.o
	$(CC) $(CFLAGS) 10_36.cpp -o 10_36.o
	$(CC) $(CFLAGS) 10_37.cpp -o 10_37.o

clean:
	rm -rf *.o
