CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 9_2.cpp -o 9_2.o 
	$(CC) $(CFLAGS) 9_4.cpp -o 9_4.o 
	$(CC) $(CFLAGS) 9_14.cpp -o 9_14.o 
	$(CC) $(CFLAGS) 9_15.cpp -o 9_15.o 
	$(CC) $(CFLAGS) 9_18.cpp -o 9_18.o 
	$(CC) $(CFLAGS) 9_19.cpp -o 9_19.o 
	$(CC) $(CFLAGS) 9_20.cpp -o 9_20.o 
	$(CC) $(CFLAGS) 9_21.cpp -o 9_21.o 
	$(CC) $(CFLAGS) 9_24.cpp -o 9_24.o 
	$(CC) $(CFLAGS) 9_25.cpp -o 9_25.o 
	$(CC) $(CFLAGS) 9_26.cpp -o 9_26.o 
	$(CC) $(CFLAGS) 9_27.cpp -o 9_27.o 
	$(CC) $(CFLAGS) 9_28.cpp -o 9_28.o 
	$(CC) $(CFLAGS) 9_31.cpp -o 9_31.o 
	$(CC) $(CFLAGS) 9_38.cpp -o 9_38.o 
	$(CC) $(CFLAGS) 9_40.cpp -o 9_40.o 
	$(CC) $(CFLAGS) 9_41.cpp -o 9_41.o 
	$(CC) $(CFLAGS) 9_43.cpp -o 9_43.o 
	$(CC) $(CFLAGS) 9_44.cpp -o 9_44.o 
	$(CC) $(CFLAGS) 9_45.cpp -o 9_45.o 
	$(CC) $(CFLAGS) 9_46.cpp -o 9_46.o 
	$(CC) $(CFLAGS) 9_47.cpp -o 9_47.o 
	$(CC) $(CFLAGS) 9_49.cpp -o 9_49.o 
	$(CC) $(CFLAGS) 9_50.cpp -o 9_50.o 
	$(CC) $(CFLAGS) 9_51.cpp -o 9_51.o 

clean:
	rm -rf *.o
