CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 3_28.cpp -o 3_28.o 
	$(CC) $(CFLAGS) 3_31.cpp -o 3_31.o 
	$(CC) $(CFLAGS) 3_32.cpp -o 3_32.o 
	$(CC) $(CFLAGS) 3_35.cpp -o 3_35.o 
	$(CC) $(CFLAGS) 3_36.cpp -o 3_36.o 
	$(CC) $(CFLAGS) 3_37.cpp -o 3_37.o 
	$(CC) $(CFLAGS) 3_39.cpp -o 3_39.o 
	$(CC) $(CFLAGS) 3_40.cpp -o 3_40.o 
	$(CC) $(CFLAGS) 3_41.cpp -o 3_41.o 
	$(CC) $(CFLAGS) 3_42.cpp -o 3_42.o 
	$(CC) $(CFLAGS) 3_43.cpp -o 3_43.o 
clean:
	rm -rf *.o
