CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 4_10.cpp -o 4_10.o 
	$(CC) $(CFLAGS) 4_13.cpp -o 4_13.o 
	$(CC) $(CFLAGS) 4_21.cpp -o 4_21.o 
	$(CC) $(CFLAGS) 4_28.cpp -o 4_28.o 
	$(CC) $(CFLAGS) 4_29.cpp -o 4_29.o 
clean:
	rm -rf *.o
