CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 6_4.cpp -o 6_4.o 
	$(CC) $(CFLAGS) 6_5.cpp -o 6_5.o 
	$(CC) $(CFLAGS) 6_7.cpp -o 6_7.o 
	$(CC) $(CFLAGS) 6_10.cpp -o 6_10.o 
	$(CC) $(CFLAGS) 6_12.cpp -o 6_12.o 
	$(CC) $(CFLAGS) 6_17.cpp -o 6_17.o 
	$(CC) $(CFLAGS) 6_21.cpp -o 6_21.o 
	$(CC) $(CFLAGS) 6_22.cpp -o 6_22.o 
	$(CC) $(CFLAGS) 6_25.cpp -o 6_25.o 
	$(CC) $(CFLAGS) 6_26.cpp -o 6_26.o 
	$(CC) $(CFLAGS) 6_27.cpp -o 6_27.o 
	$(CC) $(CFLAGS) 6_56.cpp -o 6_56.o 

clean:
	rm -rf *.o
