CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 8_1.cpp -o 8_1.o 
	$(CC) $(CFLAGS) 8_4.cpp -o 8_4.o 
	$(CC) $(CFLAGS) 8_5.cpp -o 8_5.o 
	$(CC) $(CFLAGS) 8_10.cpp -o 8_10.o 

clean:
	rm -rf *.o
