CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 5_5.cpp -o 5_5.o 
	$(CC) $(CFLAGS) 5_6.cpp -o 5_6.o 
	$(CC) $(CFLAGS) 5_9.cpp -o 5_9.o 
	$(CC) $(CFLAGS) 5_10.cpp -o 5_10.o 
	$(CC) $(CFLAGS) 5_11.cpp -o 5_11.o 
	$(CC) $(CFLAGS) 5_12.cpp -o 5_12.o 
	$(CC) $(CFLAGS) 5_14.cpp -o 5_14.o 
	$(CC) $(CFLAGS) 5_17.cpp -o 5_17.o 
	$(CC) $(CFLAGS) 5_19.cpp -o 5_19.o 
	$(CC) $(CFLAGS) 5_20.cpp -o 5_20.o 
	$(CC) $(CFLAGS) 5_23.cpp -o 5_23.o 
	$(CC) $(CFLAGS) 5_24.cpp -o 5_24.o 
clean:
	rm -rf *.o
