CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 13_11.cpp -o 13_11.o 
	$(CC) $(CFLAGS) 13_13.cpp -o 13_13.o 
	$(CC) $(CFLAGS) 13_14.cpp -o 13_14.o 
	$(CC) $(CFLAGS) 13_15.cpp -o 13_15.o 
	$(CC) $(CFLAGS) 13_16.cpp -o 13_16.o 

clean:
	rm -rf *.o
