CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 11_3.cpp -o 11_3.o 
	$(CC) $(CFLAGS) 11_4.cpp -o 11_4.o 
	$(CC) $(CFLAGS) 11_7.cpp -o 11_7.o 
	$(CC) $(CFLAGS) 11_8.cpp -o 11_8.o 
	$(CC) $(CFLAGS) 11_12.cpp -o 11_12.o 
	$(CC) $(CFLAGS) 11_14.cpp -o 11_14.o 
	$(CC) $(CFLAGS) 11_20.cpp -o 11_20.o 
	$(CC) $(CFLAGS) 11_31.cpp -o 11_31.o 
	$(CC) $(CFLAGS) 11_32.cpp -o 11_32.o 
	$(CC) $(CFLAGS) 11_33.cpp -o 11_33.o 


clean:
	rm -rf *.o
