CC = g++
CFLAGS = -Wall -std=c++11

all:
	$(CC) $(CFLAGS) 3_21.cpp -o 3_21.o 
	$(CC) $(CFLAGS) 3_22.cpp -o 3_22.o 
	$(CC) $(CFLAGS) 3_23.cpp -o 3_23.o 
	$(CC) $(CFLAGS) 3_24.cpp -o 3_24.o 
	$(CC) $(CFLAGS) 3_25.cpp -o 3_25.o 
clean:
	rm -rf *.o
