CC = g++
CFLAGS = -Wall -std=c++11

all:
	
	$(CC) $(CFLAGS) 1_3.cpp -o 1_3.o 
	$(CC) $(CFLAGS) 1_4.cpp -o 1_4.o 
	$(CC) $(CFLAGS) 1_9.cpp -o 1_9.o 
	$(CC) $(CFLAGS) 1_10.cpp -o 1_10.o 
	$(CC) $(CFLAGS) 1_11.cpp -o 1_11.o 
	$(CC) $(CFLAGS) 1_16.cpp -o 1_16.o 
clean:
	rm -rf *.o
